### PR TITLE
CSS Refactor for Responsive Design and Button Refactor CSS

### PR DESCRIPTION
**Pull request by varun13169**
Add new secondary button and link css

Refactor existing button css

Add new color in root

### CODE REVIEW

**Comment by itsmebipul00** [comment]
Nice work! Good to merge

**Review by srishtigautam21 — APPROVED** [review]
the code looks fine to me.....good to merge

**Review by zoef-yt — APPROVED** [review]
Good to merge.

**Review by sudipkundu999 — APPROVED** [review]
Looks good! Good to merge

**Pull request merged**
