### PR TITLE
Add Badge Component

### PR DESCRIPTION
**Pull request by varun13169**
Add Badge Component
	- badge html and css file.

Update documentation structure, minor changes.

Update utility css for component

### CODE REVIEW

**Comment by archit7448** [comment]
notification icon above text is small for clearly seeing it and far from the text and icon else everything looks good to merge

**Review by zoef-yt — APPROVED** [review]
All looks good. Good to merge.

**Comment by srishtigautam21** [comment]
i am not sure but i think inline styling is not allowed...please check the LMS once

**Comment by zoef-yt** [comment]
> i am not sure but i think inline styling is not allowed...please check the LMS once

He is using internal styling mostly for the showcase and not as a component library.

**Review by archit7448 — APPROVED** [review]

**Comment by varun13169** [comment]
> notification icon above text is small for clearly seeing it and far from the text and icon else everything looks good to merge

Made the content inside badge larger.

**Pull request merged**
